### PR TITLE
use trusty for hhvm

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by dbu** [comment]
@ElectricMaxxx looks like something is off here between resources and sonata. can you have a look please?

**Comment by ElectricMaxxx** [comment]
Yep, hopefully tonight.

**Comment by ElectricMaxxx** [comment]
@dbu you have to include a routing xml file from `SonataDoctrinePhpcrAdminBunde` as it is(hopefully) done in sandbox. That needs to be done in test's application config. The webtests display the tree and need that route.

**Comment by dbu** [comment]
the doc was not updated. i added: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/461

found that tree.xml already exists in version 1 but seems to not have been required.

**Pull request merged**
