### PR TITLE
cmf_block.imagine.imagine_admin no longer exists

### PR DESCRIPTION
**Pull request by binhle410**
**cmf_block.imagine.imagine_admin** no longer exists so it should be changed to **cmf_sonata_admin_integration.block.imagine.imagine_admin**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Oh. It was me, who forgot that. You see any other references between admins? 
Maybe you can add a webtest that this does not happen again?

**Comment by binhle410** [comment]
I'll try, thanks for your suggestions

**Comment by ElectricMaxxx** [comment]
There is more broken then the service injection only. 
We miss the medea-bundle here, to use the `ImageType` for the form.

@binhle410 would you like to fix that too?

means: 
medea-bundle -> require-dev
medea-bundle -> suggestions

simple web tests (maybe 200 checks) for imagine and slideshow admin.

**Comment by wouterj** [comment]
Given that we abandoned the MediaBundle, should we add these admins? Imo,removing makes the much sense.

**Comment by ElectricMaxxx** [comment]
@wouterj i whanted to start using them on a personal project. But from a practical position, you are right.

**Comment by binhle410** [comment]
So, the CmfMediaBundle shall be abandoned and removed in the next major released ?

**Comment by wouterj** [comment]
@binhle410 see https://github.com/symfony-cmf/symfony-cmf/wiki/CMF-Packages#abandoned-packages . We simply do not have the time and people to maintain all bundles, so we decided to remove some of them. If you have time left and think these bundles are extremely usefull, please feel free to start working on them and joining the team :)

**Comment by ElectricMaxxx** [comment]
@binhle410 i think we won't remove it. we will simply  stop maintaining it. but i would be very happy if you would join and we can keep the bundle alive. I have got a personal interrest into media bundle as i curently need that. so i forked it and made phpcr-odm 2.0 and did tbe stuff we did for the other maintained bundles. that means you won't be alone.

**Comment by binhle410** [comment]
Ok, I am interested in the CmfMediaBundle also, If I m not alone then, great ... Count me in :-D

**Comment by wouterj** [comment]
Created https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/pull/86, which removes the ImagineBlock as the CmfMediaBundle is abandoned atm. When the MediaBundle is alive again, we can simply re-introduce this admin.

**Comment by dbu** [comment]
merged #86. if media bundle gets fully active again we can re-add the admins cand clean things up there.

**Pull request closed without merging**
