### PR TITLE
[WIP] add phpcr into parameter fetch of routing basepath

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
I currently implement the changes in the sandbox and so i keep this open until sandbox works again.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
@wouterj can you update (re-create) the packagist hook, please?

I wanna fetch this branch in the sandbox.

**Comment by wouterj** [comment]
Auto-update is working now. Got a wrong username...

**Comment by ElectricMaxxx** [comment]
@wouterj i also added a wrong wouter some weeks ago. :-)

**Comment by wouterj** [comment]
Btw, feel free to merge this one.

**Comment by ElectricMaxxx** [comment]
looks good now on sandbox.

**Pull request merged**
